/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_graphictools_GraphicToolsJni */

#ifndef _Included_com_android_graphictools_GraphicToolsJni
#define _Included_com_android_graphictools_GraphicToolsJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_graphictools_GraphicToolsJni
 * Method:    Init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_graphictools_GraphicToolsJni_Init
  (JNIEnv *, jobject);

/*
 * Class:     com_android_graphictools_GraphicToolsJni
 * Method:    Operate
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_graphictools_GraphicToolsJni_Operate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_android_graphictools_GraphicToolsJni
 * Method:    Destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_graphictools_GraphicToolsJni_Destory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
