/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_graphictools_GraphicToolsJni */

#include <android/log.h>
#define LOG_TAG "GraphicToolsJni::"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG,LOG_TAG,__VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)

#ifndef _Included_com_android_graphictools_GraphicToolsJni
#define _Included_com_android_graphictools_GraphicToolsJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_graphictools_GraphicToolsJni
 * Method:    Init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_graphictools_GraphicToolsJni_Init
  (JNIEnv *, jobject) {
    LOGD("GraphicTools jni init");
    return true;
}

/*
 * Class:     com_android_graphictools_GraphicToolsJni
 * Method:    Operate
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_graphictools_GraphicToolsJni_Operate
  (JNIEnv *, jobject, jint operate){
    LOGD("GraphicTools jni operate %d", operate);
    return false;
}

/*
 * Class:     com_android_graphictools_GraphicToolsJni
 * Method:    Destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_graphictools_GraphicToolsJni_Destory
  (JNIEnv *, jobject){
    LOGD("GraphicTools jni destory");
    return ;
}

#ifdef __cplusplus
}
#endif
#endif
